# Generated by Django 4.2.3 on 2023-07-25 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='is_approved',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
