# Generated by Django 4.2.3 on 2023-07-27 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectTask', '0002_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.CharField(choices=[('NEW', 'NEW'), ('PENDING', 'PENDING'), ('IN PROGRESS', 'IN PROGRESS'), ('COMPLETED', 'COMPLETED')], default='NEW', max_length=11),
        ),
    ]
