# Generated by Django 4.2.3 on 2023-07-09 05:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='checked_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visitor',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='unique_identifier',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
