# Generated by Django 4.2.3 on 2023-07-09 13:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0002_visitor_checked_in_visitor_qr_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='email',
            field=models.EmailField(default='', max_length=254, validators=[django.core.validators.EmailValidator()]),
            preserve_default=False,
        ),
    ]
